CREATE TABLE EMPLOYEE( 
EMPLOYEE_ID INT NOT NULL,
EMP_FIRSTNAME VARCHAR2(30) NOT NULL,
EMP_LASTNAME VARCHAR2(30) NOT NULL,
DEPARTMENT_ID INT NOT NULL,
SALARY DECIMAL(18,2) NOT NULL,
EMP_EMAIL VARCHAR2(30) NOT NULL,
PRIMARY KEY(EMPLOYEE_ID));

CREATE TABLE DEPARTMENT(
DEPARTMENT_NAME VARCHAR2(30) NOT NULL,
DEPARTMENT_ID INT NOT NULL
);

ALTER TABLE DEPARTMENT
ADD CONSTRAINT PK_DEPARTMENT_NAME
        PRIMARY KEY (DEPARTMENT_NAME);

ALTER TABLE DEPARTMENT
ADD CONSTRAINT FK_DEPARTMENT_ID
        FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENT (DEPARTMENT_ID);
/
COMMIT;
/

CREATE SEQUENCE EMPLOYEESEQ
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    CACHE 20;
/

CREATE SEQUENCE DEPARTMENTSEQ
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    CACHE 20;
/

CREATE OR REPLACE TRIGGER INCREMENT_ON_INSERT_EMPLOYEE
    BEFORE INSERT ON EMPLOYEE
    FOR EACH ROW
    WHEN (NEW.EMPLOYEE_ID IS NULL)
    BEGIN
    SELECT EMPLOYEESEQ.NEXTVAL
    INTO :NEW.EMPLOYEE_ID
    FROM DUAL;
    END;
/

CREATE OR REPLACE TRIGGER INCREMENT_ON_INSERT_DEPARTMENT
    BEFORE INSERT ON DEPARTMENT
    FOR EACH ROW
    WHEN (NEW.DEPARTMENT_ID IS NULL)
    BEGIN
    SELECT DEPARTMENTSEQ.NEXTVAL
    INTO :NEW.DEPARTMENT_ID
    FROM DUAL;
    END;
/

INSERT INTO EMPLOYEE (emp_firstname, emp_lastname,department_id,salary,emp_email) VALUES('George','Washington','100',100000,'georgewash@president.com');
INSERT INTO EMPLOYEE (emp_firstname, emp_lastname,department_id,salary,emp_email) VALUES('John','Adams','200',200000,'jadams@president.com');
INSERT INTO EMPLOYEE (emp_firstname, emp_lastname,department_id,salary,emp_email) VALUES('Abe','Lincoln','300',300000,'pennywise@president.com');
INSERT INTO EMPLOYEE (emp_firstname, emp_lastname,department_id,salary,emp_email) VALUES('Theodore','Rosevelt','400',500000,'teddybear@president.com');
INSERT INTO EMPLOYEE (emp_firstname, emp_lastname,department_id,salary,emp_email) VALUES('John','Kennedy','500',500000,'jfk@president.com');
INSERT INTO EMPLOYEE(emp_firstname, emp_lastname,department_id,salary,emp_email) VALUES('Barrack','Obama','600',600000,'fbp@president.com');
/
COMMIT;
/

INSERT INTO DEPARTMENT (DEPARTMENT_NAME) VALUES('Oval Office');
INSERT INTO DEPARTMENT (DEPARTMENT_NAME) VALUES('Leader of USA');
INSERT INTO DEPARTMENT (DEPARTMENT_NAME) VALUES('Commander');
/
COMMIT;
/